# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/software/cmake-3.23.2/bin/cmake

# The command to remove a file.
RM = /usr/local/software/cmake-3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /rwproject/kdd-db/students/wtanae/project/webank/CCFD_mining

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /rwproject/kdd-db/students/wtanae/project/webank/CCFD_mining

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/software/cmake-3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/software/cmake-3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /rwproject/kdd-db/students/wtanae/project/webank/CCFD_mining/CMakeFiles /rwproject/kdd-db/students/wtanae/project/webank/CCFD_mining//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /rwproject/kdd-db/students/wtanae/project/webank/CCFD_mining/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CFDMiner

# Build rule for target.
CFDMiner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CFDMiner
.PHONY : CFDMiner

# fast build rule for target.
CFDMiner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/build
.PHONY : CFDMiner/fast

#=============================================================================
# Target rules for targets named CFDMiner_Graph

# Build rule for target.
CFDMiner_Graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CFDMiner_Graph
.PHONY : CFDMiner_Graph

# fast build rule for target.
CFDMiner_Graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/build
.PHONY : CFDMiner_Graph/fast

#=============================================================================
# Target rules for targets named FGC_Stream_CFDMiner

# Build rule for target.
FGC_Stream_CFDMiner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FGC_Stream_CFDMiner
.PHONY : FGC_Stream_CFDMiner

# fast build rule for target.
FGC_Stream_CFDMiner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/build
.PHONY : FGC_Stream_CFDMiner/fast

FGC-Stream/FGC-Stream.o: FGC-Stream/FGC-Stream.cpp.o
.PHONY : FGC-Stream/FGC-Stream.o

# target to build an object file
FGC-Stream/FGC-Stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/FGC-Stream.cpp.o
.PHONY : FGC-Stream/FGC-Stream.cpp.o

FGC-Stream/FGC-Stream.i: FGC-Stream/FGC-Stream.cpp.i
.PHONY : FGC-Stream/FGC-Stream.i

# target to preprocess a source file
FGC-Stream/FGC-Stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/FGC-Stream.cpp.i
.PHONY : FGC-Stream/FGC-Stream.cpp.i

FGC-Stream/FGC-Stream.s: FGC-Stream/FGC-Stream.cpp.s
.PHONY : FGC-Stream/FGC-Stream.s

# target to generate assembly for a file
FGC-Stream/FGC-Stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/FGC-Stream.cpp.s
.PHONY : FGC-Stream/FGC-Stream.cpp.s

FGC-Stream/main.o: FGC-Stream/main.cpp.o
.PHONY : FGC-Stream/main.o

# target to build an object file
FGC-Stream/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/main.cpp.o
.PHONY : FGC-Stream/main.cpp.o

FGC-Stream/main.i: FGC-Stream/main.cpp.i
.PHONY : FGC-Stream/main.i

# target to preprocess a source file
FGC-Stream/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/main.cpp.i
.PHONY : FGC-Stream/main.cpp.i

FGC-Stream/main.s: FGC-Stream/main.cpp.s
.PHONY : FGC-Stream/main.s

# target to generate assembly for a file
FGC-Stream/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/FGC-Stream/main.cpp.s
.PHONY : FGC-Stream/main.cpp.s

algorithms/clogenmerger.o: algorithms/clogenmerger.cpp.o
.PHONY : algorithms/clogenmerger.o

# target to build an object file
algorithms/clogenmerger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenmerger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenmerger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenmerger.cpp.o
.PHONY : algorithms/clogenmerger.cpp.o

algorithms/clogenmerger.i: algorithms/clogenmerger.cpp.i
.PHONY : algorithms/clogenmerger.i

# target to preprocess a source file
algorithms/clogenmerger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenmerger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenmerger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenmerger.cpp.i
.PHONY : algorithms/clogenmerger.cpp.i

algorithms/clogenmerger.s: algorithms/clogenmerger.cpp.s
.PHONY : algorithms/clogenmerger.s

# target to generate assembly for a file
algorithms/clogenmerger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenmerger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenmerger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenmerger.cpp.s
.PHONY : algorithms/clogenmerger.cpp.s

algorithms/clogenminer.o: algorithms/clogenminer.cpp.o
.PHONY : algorithms/clogenminer.o

# target to build an object file
algorithms/clogenminer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenminer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenminer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenminer.cpp.o
.PHONY : algorithms/clogenminer.cpp.o

algorithms/clogenminer.i: algorithms/clogenminer.cpp.i
.PHONY : algorithms/clogenminer.i

# target to preprocess a source file
algorithms/clogenminer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenminer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenminer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenminer.cpp.i
.PHONY : algorithms/clogenminer.cpp.i

algorithms/clogenminer.s: algorithms/clogenminer.cpp.s
.PHONY : algorithms/clogenminer.s

# target to generate assembly for a file
algorithms/clogenminer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/clogenminer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/clogenminer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/clogenminer.cpp.s
.PHONY : algorithms/clogenminer.cpp.s

algorithms/minernode.o: algorithms/minernode.cpp.o
.PHONY : algorithms/minernode.o

# target to build an object file
algorithms/minernode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/minernode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/minernode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/minernode.cpp.o
.PHONY : algorithms/minernode.cpp.o

algorithms/minernode.i: algorithms/minernode.cpp.i
.PHONY : algorithms/minernode.i

# target to preprocess a source file
algorithms/minernode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/minernode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/minernode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/minernode.cpp.i
.PHONY : algorithms/minernode.cpp.i

algorithms/minernode.s: algorithms/minernode.cpp.s
.PHONY : algorithms/minernode.s

# target to generate assembly for a file
algorithms/minernode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/algorithms/minernode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/algorithms/minernode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/algorithms/minernode.cpp.s
.PHONY : algorithms/minernode.cpp.s

data/database.o: data/database.cpp.o
.PHONY : data/database.o

# target to build an object file
data/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/database.cpp.o
.PHONY : data/database.cpp.o

data/database.i: data/database.cpp.i
.PHONY : data/database.i

# target to preprocess a source file
data/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/database.cpp.i
.PHONY : data/database.cpp.i

data/database.s: data/database.cpp.s
.PHONY : data/database.s

# target to generate assembly for a file
data/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/database.cpp.s
.PHONY : data/database.cpp.s

data/dbtoken.o: data/dbtoken.cpp.o
.PHONY : data/dbtoken.o

# target to build an object file
data/dbtoken.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/dbtoken.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/dbtoken.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/dbtoken.cpp.o
.PHONY : data/dbtoken.cpp.o

data/dbtoken.i: data/dbtoken.cpp.i
.PHONY : data/dbtoken.i

# target to preprocess a source file
data/dbtoken.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/dbtoken.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/dbtoken.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/dbtoken.cpp.i
.PHONY : data/dbtoken.cpp.i

data/dbtoken.s: data/dbtoken.cpp.s
.PHONY : data/dbtoken.s

# target to generate assembly for a file
data/dbtoken.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/dbtoken.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/dbtoken.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/dbtoken.cpp.s
.PHONY : data/dbtoken.cpp.s

data/itemsetdatabase.o: data/itemsetdatabase.cpp.o
.PHONY : data/itemsetdatabase.o

# target to build an object file
data/itemsetdatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/itemsetdatabase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/itemsetdatabase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/itemsetdatabase.cpp.o
.PHONY : data/itemsetdatabase.cpp.o

data/itemsetdatabase.i: data/itemsetdatabase.cpp.i
.PHONY : data/itemsetdatabase.i

# target to preprocess a source file
data/itemsetdatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/itemsetdatabase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/itemsetdatabase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/itemsetdatabase.cpp.i
.PHONY : data/itemsetdatabase.cpp.i

data/itemsetdatabase.s: data/itemsetdatabase.cpp.s
.PHONY : data/itemsetdatabase.s

# target to generate assembly for a file
data/itemsetdatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/itemsetdatabase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/itemsetdatabase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/itemsetdatabase.cpp.s
.PHONY : data/itemsetdatabase.cpp.s

data/tabulardatabase.o: data/tabulardatabase.cpp.o
.PHONY : data/tabulardatabase.o

# target to build an object file
data/tabulardatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/tabulardatabase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/tabulardatabase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/tabulardatabase.cpp.o
.PHONY : data/tabulardatabase.cpp.o

data/tabulardatabase.i: data/tabulardatabase.cpp.i
.PHONY : data/tabulardatabase.i

# target to preprocess a source file
data/tabulardatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/tabulardatabase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/tabulardatabase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/tabulardatabase.cpp.i
.PHONY : data/tabulardatabase.cpp.i

data/tabulardatabase.s: data/tabulardatabase.cpp.s
.PHONY : data/tabulardatabase.s

# target to generate assembly for a file
data/tabulardatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/data/tabulardatabase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/data/tabulardatabase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/data/tabulardatabase.cpp.s
.PHONY : data/tabulardatabase.cpp.s

main_CFDMiner.o: main_CFDMiner.cpp.o
.PHONY : main_CFDMiner.o

# target to build an object file
main_CFDMiner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/main_CFDMiner.cpp.o
.PHONY : main_CFDMiner.cpp.o

main_CFDMiner.i: main_CFDMiner.cpp.i
.PHONY : main_CFDMiner.i

# target to preprocess a source file
main_CFDMiner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/main_CFDMiner.cpp.i
.PHONY : main_CFDMiner.cpp.i

main_CFDMiner.s: main_CFDMiner.cpp.s
.PHONY : main_CFDMiner.s

# target to generate assembly for a file
main_CFDMiner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/main_CFDMiner.cpp.s
.PHONY : main_CFDMiner.cpp.s

main_graph.o: main_graph.cpp.o
.PHONY : main_graph.o

# target to build an object file
main_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/main_graph.cpp.o
.PHONY : main_graph.cpp.o

main_graph.i: main_graph.cpp.i
.PHONY : main_graph.i

# target to preprocess a source file
main_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/main_graph.cpp.i
.PHONY : main_graph.cpp.i

main_graph.s: main_graph.cpp.s
.PHONY : main_graph.s

# target to generate assembly for a file
main_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/main_graph.cpp.s
.PHONY : main_graph.cpp.s

util/setutil.o: util/setutil.cpp.o
.PHONY : util/setutil.o

# target to build an object file
util/setutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/util/setutil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/util/setutil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/util/setutil.cpp.o
.PHONY : util/setutil.cpp.o

util/setutil.i: util/setutil.cpp.i
.PHONY : util/setutil.i

# target to preprocess a source file
util/setutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/util/setutil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/util/setutil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/util/setutil.cpp.i
.PHONY : util/setutil.cpp.i

util/setutil.s: util/setutil.cpp.s
.PHONY : util/setutil.s

# target to generate assembly for a file
util/setutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner.dir/build.make CMakeFiles/CFDMiner.dir/util/setutil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CFDMiner_Graph.dir/build.make CMakeFiles/CFDMiner_Graph.dir/util/setutil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FGC_Stream_CFDMiner.dir/build.make CMakeFiles/FGC_Stream_CFDMiner.dir/util/setutil.cpp.s
.PHONY : util/setutil.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CFDMiner"
	@echo "... CFDMiner_Graph"
	@echo "... FGC_Stream_CFDMiner"
	@echo "... FGC-Stream/FGC-Stream.o"
	@echo "... FGC-Stream/FGC-Stream.i"
	@echo "... FGC-Stream/FGC-Stream.s"
	@echo "... FGC-Stream/main.o"
	@echo "... FGC-Stream/main.i"
	@echo "... FGC-Stream/main.s"
	@echo "... algorithms/clogenmerger.o"
	@echo "... algorithms/clogenmerger.i"
	@echo "... algorithms/clogenmerger.s"
	@echo "... algorithms/clogenminer.o"
	@echo "... algorithms/clogenminer.i"
	@echo "... algorithms/clogenminer.s"
	@echo "... algorithms/minernode.o"
	@echo "... algorithms/minernode.i"
	@echo "... algorithms/minernode.s"
	@echo "... data/database.o"
	@echo "... data/database.i"
	@echo "... data/database.s"
	@echo "... data/dbtoken.o"
	@echo "... data/dbtoken.i"
	@echo "... data/dbtoken.s"
	@echo "... data/itemsetdatabase.o"
	@echo "... data/itemsetdatabase.i"
	@echo "... data/itemsetdatabase.s"
	@echo "... data/tabulardatabase.o"
	@echo "... data/tabulardatabase.i"
	@echo "... data/tabulardatabase.s"
	@echo "... main_CFDMiner.o"
	@echo "... main_CFDMiner.i"
	@echo "... main_CFDMiner.s"
	@echo "... main_graph.o"
	@echo "... main_graph.i"
	@echo "... main_graph.s"
	@echo "... util/setutil.o"
	@echo "... util/setutil.i"
	@echo "... util/setutil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

